### ISSUE TITLE
How to build? 

### ISSUE THREAD

**Issue by trlef19** [deadwood2/OdysseyWebBrowser#5]
I'm a little confused with that. Can we have more specific directions on how to build it?

**Comment by deadwood2** [comment]
Which target are you planning to build?

**Comment by trlef19** [comment]
release, i guess. Unless you recommend something else :))

**Comment by deadwood2** [comment]
Sorry, I meant which architecture - i386 or x86_64. Additional question - do you already have AROS cross compiler and SDK built and installed on your machine?

**Comment by trlef19** [comment]
Oh. X64. No I don't 😅. Is it possible you could offer executables?

**Comment by deadwood2** [comment]
You will need to have cross compilers and SDK built locally on your machine - I will share tutorials later today.

BTW, do you want do develop/make changes to Odyssey or test how it works under AROS? If the later, then there is already an Odyssey binary available.

**Comment by deadwood2** [comment]
I updated the README.md with instructions on how to build. If you use Discord, please consider joining https://discord.gg/CFjnnzhq in case you have additional questions.

**Comment by deadwood2** [comment]
Ok, if you just wanted to try it, it makes things much easier.

Here are 3 tutorial depending on what OS you run:
https://arosnews.github.io/OWB-axrt-wsl2/
https://arosnews.github.io/OWB-axrt-linux/
https://arosnews.github.io/OWB-aros-linux-hosted/

Please keep in mind that Odyssey 64-bit is still BETA so there might be fixes compared to version described in these tutorials.

**Comment by deadwood2** [comment]
I assume you got it to run, if not please join discord for more help. Closing this issue.
